[package]
name = "zap"
version = "0.1.0"
authors = ["Josh Leverette <coder543@gmail.com>"]

[dev-dependencies]
criterion = "0.2.3"
handlebars = "0.32.0"
serde_json = "1.0.16"
serde_derive = "1.0.43"
serde = "1.0.43"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
serde = "1.0.43"
